twig:
    default_path: '%kernel.project_dir%/templates'
    globals:
        dashboard: '@App\Services\DashboardService'
        google_maps_api_key: '%env(MAPS_API_KEY)%'
    form_themes: ['form.html.twig']
